const firebaseConfig = {
  apiKey: "AIzaSyARiREVh3N4tsEeJhqNzMB70R1ZA9IiRtc",
  authDomain: "clinicbrain-b1215.firebaseapp.com",
  databaseURL: "https://clinicbrain-b1215-default-rtdb.firebaseio.com",
  projectId: "clinicbrain-b1215",
  storageBucket: "clinicbrain-b1215.appspot.com",
  messagingSenderId: "142661610441",
  appId: "1:142661610441:web:4572c6354e428a6823d618"
};
  // Initialize Firebase
  firebase.initializeApp(firebaseConfig);
var password = "";
if(localStorage.getItem('verify') == "yes"){
    window.location = 'main.html';
}
var Username = "";
var Password = "";
var getU = "";
var getP = "";
  function sendotp(){
  Username = document.getElementById('Username').value;
  Password = document.getElementById('password').value;

  if (Username != "" && Password != ""){
  var ref = firebase.database().ref('VerifyUser/');
  ref.once('value',function(get_data){
  var data = get_data.val();
  getU = data.Name;
  getP = data.Password;
  });
  setTimeout(function(){

  if(getU == Username && getP == Password){
    password = "no";
   sendotp55();
  }else{
    alert('Invalid Username And Password');
  }
  },2000)
  }else{
    alert('Some Strings Are Missing.')
  }
  }
o=0;
function sendotp55(){
  document.getElementById('login_div').style.display = "none";
  document.getElementById('otp123').style.display = "block";
  document.getElementById('newpassword').style.display = "none";
  //CF5B5693E1B1BCF15363447DC199BDC45B28
  //clinicbrainbot@gmail.com
  //f196c33d-9ffd-4bc3-8e3b-769190854a7f
  o = Math.floor(Math.random()*1000000)
  let OTP = "𝙋𝙡𝙚𝙖𝙨𝙚 𝙀𝙣𝙩𝙚𝙧 𝙏𝙝𝙚 𝙊𝙏𝙋 "+o;
setTimeout(function(){
  Email.send({
    SecureToken : "59d130ea-b307-44ac-95cb-e44b232dd24e",
    To : 'arkabhattacharyac42@gmail.com',
    From : "clinicbrainbot@gmail.com",
    Subject : "This is a AutoGenerated Mail.",
    Body : OTP
}).then(
  message => {
    if(message === "OK"){
        alert("OTP SENDED TO THE REGISTER EMAIL ID")
    }else{
        alert('NETWORK ERROR TRY AGAIN.')
    }
  }
);
},2000)
  

}
function verifyotp(){
    if(document.getElementById('otp').value == o){
        if(password != "yes"){
            localStorage.setItem('verify','yes')
            window.location = 'main.html'
        }else if(password == "yes"){
            document.getElementById('login_div').style.display = "none";
            document.getElementById('otp123').style.display = "none";
            document.getElementById('newpassword').style.display = "block";
        }else{
            return false
        }

       
    }else{
        alert('Incorrect Otp.')
    }
}
function forgot(){
    password = "yes"
    sendotp55();
}
function remember(){
    document.getElementById('login_div').style.display = "block";
    document.getElementById('otp123').style.display = "none";
    document.getElementById('newpassword').style.display = "none";
}
function newpassword(){
    if (document.getElementById('password12').value != ""){
    firebase.database().ref('VerifyUser/').update({
   Name:"DrGautamSaha20140075",
   Password:document.getElementById('password12').value
    });
    document.getElementById('login_div').style.display = "block";
    document.getElementById('otp123').style.display = "none";
    document.getElementById('newpassword').style.display = "none";
    }else{
      return false
    }
}